
* Issue tracker for Koi Editor

[[https://github.com/hackermanai/koi/issues][Submit feature request or report bug]]


** How to use inline shell and chat

Inline commands can be triggered with /Inline Commands/ (or ~Cmd + Shift + Return~).

*Shell and Python eval*

This feature is only allowed in Generic-Default, ~.txt~, ~.md~, ~.org~ files by default.
You can change allowed files in your ~.hackerman~ config file.

#+begin_src

% echo 'hello'
hello

#+begin_src
42**42
150130937545296572356771972164254457814047970568738777235893533016064

#+end_src


** How to create custom editor commands

This feature is disabled by default.
You can enable in your ~.hackerman~ config file.

#+begin_src

scripts_enabled                     true
allow_unsafe_scripts                false -- allow imports

#+end_src

User scripts are loaded from ~.../Application Support/Koi/.hackerman-scripts~.
You can provide a path to your own ~.py~ file if stored elsewhere.

#+begin_src

path_to_scripts_file                path/to/plugins.py

#+end_src


** Other tips and tricks

- Right click to /Show Command Palette/ (or ~Cmd + Shift + P~), this list shows all editor commands and key bindings
- Double click on line number to /Fold Line/ (or ~Cmd + L~)
- Double click on word to select, ~Cmd~ plus double click on another word to add to selection
- Select text then /Select Next Match/ (or ~Cmd + E~) to select next exact match, /Unselect Next Match/ (or ~Cmd + Shift + E~) to unselect last added match
- Find with /Find In File/ (or ~Cmd + F~), ~Esc~, then /Select Matches/ to select/add cursor to each match
- Select brace to highlight open and/or closing brace
- /Show File Explorer/ (or ~Cmd + P~) shows all files and folder on Desktop by default, ~my-project/~ to quickly find files in specific folders
